version: "1.0"
info:
  model: int-scaffold
packages:
- name: FLOW_TEST_NEWProject
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit/FLOW_TEST_NEWProject
  gitUsername: PoojaAnandGit
  gitBranch: main
- name: PackagesScenario
  version: "2.0"
  gitServerName: testInternal
  gitUrl: https://github.webmethods.io/munb
  gitUsername: poan
  gitBranch: branch2
- name: OpenWeatherClient
  gitServerName: test2
  gitUrl: https://github.com/rahuldemocenter
  gitUsername: PoojaAnandGit
  gitBranch: main
services:
- serviceName: project.flow_test_new.integrations:edgeflow1
  packages:
  - name: FLOW_TEST_NEWProject
    version: "1.0"
  - name: PackagesScenario
    version: "2.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.0.0.0.949
- serviceName: project.flow_test_new.integrations:e1
  packages:
  - name: FLOW_TEST_NEWProject
    version: "1.0"
  - name: PackagesScenario
    version: "2.0"
- serviceName: ANZ_POCPKg.flows:StringToValues
  packages:
  - name: PackagesScenario
    version: "2.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.873
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.0.0.0.873
- serviceName: pub.flatFile:convertToValues
  packages:
  - name: WmFlatFile
    version: 10.7.0.0.28
- serviceName: ANZ_POCPKg.javaservices:addTwoNos
  packages:
  - name: PackagesScenario
    version: "2.0"
- serviceName: pub.json:documentToJSONString
  packages:
  - name: WmPublic
    version: 11.0.0.0.873
- serviceName: pub.flatFile:convertToString
  packages:
  - name: WmFlatFile
    version: 10.7.0.0.28
- serviceName: pub.xml:documentToXMLString
  packages:
  - name: WmPublic
    version: 11.0.0.0.873
- serviceName: project.flow_test_new.integrations:testPkgDocs
  packages:
  - name: FLOW_TEST_NEWProject
    version: "1.0"
  - name: PackagesScenario
    version: "2.0"
- serviceName: project.flow_test_new.integrations:edgeflow2
  packages:
  - name: FLOW_TEST_NEWProject
    version: "1.0"
  - name: PackagesScenario
    version: "2.0"
- serviceName: project.flow_test_new.integrations:w122
  packages:
  - name: FLOW_TEST_NEWProject
    version: "1.0"
  - name: PackagesScenario
    version: "2.0"
- serviceName: pub.date:calculateDateDifference
  packages:
  - name: WmPublic
    version: 11.0.0.0.922
- serviceName: project.flow_test_new.integrations:testImportFromZip
  packages:
  - name: FLOW_TEST_NEWProject
    version: "1.0"
  - name: PackagesScenario
    version: "2.0"
  - name: OpenWeatherClient
    version: "1.0"
