version: "1.0"
info:
  model: int-scaffold
packages:
- name: FLOW_TEST_NEWProject
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit/FLOW_TEST_NEWProject
  gitUsername: PoojaAnandGit
  gitBranch: main
